[package]
name = "rusty_snake"
version = "0.1.0"
authors = ["NicolenaStiles <nicolena.stiles@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1.5.5"
tui = "0.12.0"
